;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        bgs-open-prev-line
        c-electric-delete-forward
        comint-delchar-or-maybe-eof
        company-complete
        counsel-M-x
        dabbrev-expand
        delete-indentation
        electric-newline-and-maybe-indent
        eval-last-sexp
        forward-sexp
        helm-M-x
        indent-for-tab-command
        kill-region
        mark-sexp
        org-backward-sentence
        org-beginning-of-line
        org-columns-edit-value
        org-columns-next-allowed-value
        org-columns-previous-allowed-value
        org-columns-quit
        org-ctrl-c-ctrl-c
        org-ctrl-c-ret
        org-ctrl-c-star
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-forward-sentence
        org-insert-heading-respect-content
        org-kill-line
        org-meta-return
        org-metaright
        org-return
        org-return-indent
        org-self-insert-command
        org-shiftdown
        org-shiftmetaleft
        org-shiftmetaright
        org-shiftmetaup
        org-shifttab
        org-shiftup
        org-table-blank-field
        org-yank
        smex
        vc-next-action
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        next-multiframe-window
        outline-show-children
        swiper-mc
        zygospore-toggle-delete-other-windows
        ))
