;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	helm-M-x
	mark-sexp
	org-beginning-of-line
	org-ctrl-c-ctrl-c
	org-delete-char
	org-meta-return
	org-metaright
	org-return-indent
	org-self-insert-command
	org-shiftmetaleft
	org-shiftmetaright
	smex
	))

(setq mc/cmds-to-run-once
      '(
	org-cycle
	))
